(() => {
 'use strict';
 const data=JSON.parse(document.getElementById('curriculum').textContent);
 const lessons=data.lessons, questions=new Map(), lessonById=new Map(lessons.map(l=>[l.id,l]));
 for(const lesson of lessons) for(const q of lesson.questions) questions.set(q.id,{...q,lesson:lesson.id});
 const KEY='csharp-trail-v1', main=document.getElementById('main'), dialog=document.getElementById('settings');
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rich=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>');
 const normal=s=>String(s).trim().replace(/\s+/g,' ');
 let storageAvailable=true, stored={};
 let raw='{}';try{raw=localStorage.getItem(KEY)||'{}';localStorage.setItem(KEY,raw);}catch{storageAvailable=false;}
 try{stored=JSON.parse(raw);if(!stored||typeof stored!=='object'||Array.isArray(stored))stored={};}catch{stored={};}
 function cleanResults(input){const out={};if(!input||typeof input!=='object')return out;for(const [id,r] of Object.entries(input)){if(!questions.has(id)||!r||typeof r!=='object')continue;out[id]={attempts:Number.isInteger(r.attempts)?Math.max(0,Math.min(r.attempts,100000)):0,completed:r.completed===true,firstTry:r.firstTry===true,needsReview:r.needsReview===true,helped:r.helped===true};}return out;}
 const state={view:'trail',lesson:lessonById.has(stored.lesson)?stored.lesson:lessons[0].id,results:cleanResults(stored.results),theme:stored.theme==='dark'?'dark':'light',run:[],index:0,runMode:'lesson',runOutcomes:{},draft:null};
 document.documentElement.dataset.theme=state.theme;
 const result=id=>state.results[id]||{attempts:0,completed:false,firstTry:false,needsReview:false,helped:false};
 const stats=()=>{const r=Object.values(state.results);return{completed:r.filter(x=>x.completed).length,firstTry:r.filter(x=>x.firstTry).length,review:r.filter(x=>x.needsReview).length};};
 function save(){if(!storageAvailable)return;try{localStorage.setItem(KEY,JSON.stringify({version:1,lesson:state.lesson,theme:state.theme,results:state.results}));}catch{storageAvailable=false;}}
 function toast(message){document.getElementById('toast').textContent=message;clearTimeout(toast.timer);toast.timer=setTimeout(()=>document.getElementById('toast').textContent='',4000);}
 function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 function highlight(source){
   const token=/(\/\/[^\n]*|\$?@?"(?:""|\\.|[^"\\])*"|'(?:\\.|[^'\\])'|\b(?:public|private|internal|protected|static|sealed|class|record|struct|interface|new|var|int|long|decimal|double|bool|string|void|return|if|else|foreach|for|in|is|not|or|and|null|true|false|async|await|using|namespace|try|catch|finally|throw|override|virtual|abstract|readonly|partial|yield|out|ref|params|switch|get|set|init|this|base|with)\b|\b\d+(?:\.\d+)?m?\b)/g;
   let end=0,out='',m;while((m=token.exec(source))){out+=esc(source.slice(end,m.index));const t=m[0],cls=t.startsWith('//')?'comment':/^["'$@]/.test(t)?'string':/^\d/.test(t)?'number':'key';out+=`<span class="tok-${cls}">${esc(t)}</span>`;end=token.lastIndex;}return out+esc(source.slice(end));
 }
 const code=(source,label='C# · small example')=>`<div class="code-panel"><div class="code-label">${esc(label)}</div><pre><code>${highlight(source)}</code></pre></div>`;
 function references(lesson){return lesson.reference?.length?`<details><summary>A few more symbols, when you need them</summary><dl>${lesson.reference.map(r=>`<dt>${rich(r.term)}</dt><dd>${rich(r.meaning)}</dd>`).join('')}</dl></details>`:'';}
 function lessonNotes(lesson){return `<ul class="rules">${lesson.rules.map(r=>`<li>${rich(r)}</li>`).join('')}</ul><div class="trap"><strong>Watch this distinction</strong>${rich(lesson.trap)}</div>`;}
 function progressMeter(completed,total,label){return `<div class="meter" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${completed}"><span style="width:${Math.round(completed/total*100)}%"></span></div>`;}
 function trail(){
   const s=stats(), next=lessons.find(l=>l.questions.some(q=>!result(q.id).completed))||lessons[0];
   const stages=[['Read the language','Values, functions, null and objects'],['Shape your data','Records, contracts, collections and queries'],['Follow the execution','Data, tasks, cancellation and streams'],['Put an app together','Files, JSON, HTTP and testable boundaries']];
   return `<section class="hero"><div><div class="eyebrow">From familiar Python to readable C#</div><h1>Learn a little.<br>Try a little.</h1><p class="lead">Small examples. One decision at a time. Build a feel for C# before you return to the agent code.</p><div class="hero-action"><button class="primary" data-lesson="${next.id}">${s.completed?'Continue the trail':'Start with the basics'} →</button><button class="quiet" data-action="mixed">Try 10 mixed questions</button></div></div><aside class="progress-panel"><div class="eyebrow">Your trail</div><div class="progress-title"><span class="big-number">${s.completed}</span><span class="muted">of ${questions.size} checkpoints completed</span></div>${progressMeter(s.completed,questions.size,'Completed checkpoints')}<div class="stats"><div><b>${s.firstTry}</b><span>correct first try, unaided</span></div><div><b>${s.review}</b><span>to revisit</span></div></div><p class="small" style="margin:14px 0 0">Help is welcome. A retry or hint adds the question to your review queue.</p></aside></section><div class="rule-strip"><span>${lessons.length} short lessons</span><span>Predict · fill · arrange</span><span>No timer, no locked levels</span><span>${storageAvailable?'Progress saved in this browser':'Progress lasts this visit; export to keep it'}</span></div><section class="trail-grid" aria-label="Lesson trail">${stages.map((stage,i)=>`<article class="stage"><div class="stage-number">Stage ${i+1} / 4</div><h2>${stage[0]}</h2><p>${stage[1]}</p>${lessons.slice(i*4,i*4+4).map((l,j)=>{const count=l.questions.filter(q=>result(q.id).completed).length;return `<button type="button" class="stop ${count===l.questions.length?'done':''}" data-lesson="${l.id}"><span class="number">${count===l.questions.length?'✓':String(i*4+j+1).padStart(2,'0')}</span><span>${esc(l.title)}<small>${count}/${l.questions.length} checkpoints${l.questions.some(q=>result(q.id).needsReview)?' · review waiting':''}</small></span></button>`;}).join('')}</article>`).join('')}</section><p class="small" style="margin-top:24px">You can keep writing plain functions. Classes become useful when data and behavior belong together; interfaces help when an implementation needs to be replaceable.</p>`;
 }
 function lessonPage(){const l=lessonById.get(state.lesson),n=lessons.indexOf(l)+1;return `<div class="back-row"><button type="button" class="quiet" data-action="trail">← Trail map</button><span class="small">Lesson ${n} of ${lessons.length} · read, then try four checkpoints</span></div><section class="lesson-layout"><div><div class="eyebrow">${esc(l.subtitle)}</div><h1>${esc(l.title)}</h1>${lessonNotes(l)}<div class="lesson-actions"><button type="button" class="primary" data-action="start-lesson">Try the checkpoints →</button><a class="button quiet" href="cheat-sheet.html#${esc(l.id)}" target="_blank" rel="noopener">Open in cheat sheet ↗</a></div></div><div>${code(l.code)}${l.python?`<details><summary>Connect it to Python</summary><pre>${esc(l.python)}</pre></details>`:''}${references(l)}<p class="connection"><strong>When you return to the agents:</strong> ${rich(l.agentConnection)}</p></div></section>`;}
 function newDraft(q){let order=shuffle(q.lines?.map((_,i)=>i)||[]);if(order.length&&order.every((n,i)=>n===i))order.reverse();return{id:q.id,choice:null,text:'',order,optionOrder:shuffle(q.options?.map((_,i)=>i)||[]),tries:0,hinted:false,showNote:false,revealed:false,correct:false,feedback:null};}
 function questionPage(){
   const q=questions.get(state.run[state.index]);if(!q){state.view='finish';return finish();}const l=lessonById.get(q.lesson);if(!state.draft||state.draft.id!==q.id)state.draft=newDraft(q);const d=state.draft;
   const answer=q.type==='choice'?`<fieldset style="border:0;padding:0;margin:0"><legend class="small">Choose one answer.</legend><div class="options">${d.optionOrder.map((i,j)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${d.choice===i?'checked':''} ${d.correct||d.revealed?'disabled':''}><span class="option-letter">${String.fromCharCode(65+j)}</span><span>${rich(q.options[i].text)}</span></label>`).join('')}</div></fieldset>`:q.type==='fill'?`<div class="answer-field"><label for="answer-input">Fill the blank with the requested token or expression.</label><input id="answer-input" type="text" autocomplete="off" spellcheck="false" value="${esc(d.text)}" ${d.correct||d.revealed?'disabled':''}><p class="small" style="margin:8px 0 0">Capitalization matters in C#. No need to add a semicolon unless the prompt asks for one.</p></div>`:`<p class="small">Move the lines into the required order. Read from top to bottom.</p><ol class="order-list">${d.order.map((original,i)=>`<li><span class="order-index">${i+1}</span><code>${esc(q.lines[original])}</code><span class="order-controls"><button type="button" data-move="${i}" data-direction="-1" aria-label="Move line ${i+1} up" ${i===0||d.correct||d.revealed?'disabled':''}>↑</button><button type="button" data-move="${i}" data-direction="1" aria-label="Move line ${i+1} down" ${i===d.order.length-1||d.correct||d.revealed?'disabled':''}>↓</button></span></li>`).join('')}</ol>`;
   return `<section class="challenge-wrap" data-question-id="${q.id}"><div class="back-row"><button type="button" class="quiet" data-action="trail">← Trail map</button><span class="small">${state.runMode==='lesson'?esc(l.title):state.runMode==='review'?'Review round':'Mixed practice'}</span></div><div class="challenge-top"><div><div class="eyebrow">Checkpoint ${state.index+1} of ${state.run.length} · ${q.type==='choice'?'Choose':q.type==='fill'?'Fill the gap':'Arrange'}</div><span class="small">${state.runMode==='lesson'?'One idea, one small decision.':esc(l.title)}</span></div><div class="dots" aria-hidden="true">${state.run.map((_,i)=>`<span class="dot ${i===state.index?'current':i<state.index?'complete':''}"></span>`).join('')}</div></div><article class="challenge-card"><h1>${rich(q.prompt)}</h1>${q.code?code(q.code,'C# · reason about this snippet'):''}${answer}<div id="feedback" aria-live="polite">${feedback(q,d)}</div>${d.hinted?`<div class="hint"><strong>Hint:</strong> ${rich(q.hint)}</div>`:''}<div class="answer-actions">${d.correct||d.revealed?`<button type="button" class="primary" data-action="next">${state.index===state.run.length-1?'Finish this round':'Next checkpoint'} →</button>`:`<button type="button" class="primary" data-action="check" ${q.type==='choice'&&d.choice===null||q.type==='fill'&&!d.text.trim()?'disabled':''}>Check my answer</button><button type="button" class="quiet" data-action="hint" ${d.hinted?'disabled':''}>A small hint</button>`}</div>${!d.correct&&!d.revealed?`<div class="help-actions"><button type="button" data-action="note">${d.showNote?'Hide lesson note':'Read the lesson note'}</button><button type="button" data-action="reveal">Show and explain the answer</button><button type="button" data-action="skip">Skip for now</button></div>`:''}${d.showNote?`<section style="margin-top:22px"><h2 style="font-size:20px">${esc(l.title)}</h2>${lessonNotes(l)}${code(l.code)}</section>`:''}</article><div class="challenge-footer"><span>Hints and retries create useful review questions.</span><a href="cheat-sheet.html#${esc(l.id)}" target="_blank" rel="noopener" data-cheat-help>Related cheat-sheet note ↗</a></div></section>`;
 }
 function feedback(q,d){if(!d.feedback)return'';const f=d.feedback;return `<div class="feedback ${f.kind==='wrong'?'wrong':''}"><h2>${esc(f.title)}</h2><p>${rich(f.text)}</p>${d.revealed?`<p><strong>Answer:</strong></p>${q.type==='order'?`<pre style="white-space:pre-wrap">${esc(q.lines.join('\n'))}</pre>`:`<p>${rich(q.type==='choice'?q.options[q.answer].text:q.accepted[0])}</p>`}`:''}${d.correct||d.revealed?`<p class="small">${d.revealed||d.hinted||d.tries>1?'Added to review. Try it unaided on a later visit.':'A clear, unaided answer.'}</p>`:''}</div>`;}
 function finish(){const s=stats(),completed=Object.values(state.runOutcomes).filter(x=>x!=='skipped').length,review=state.run.filter(id=>result(id).needsReview).length,l=lessonById.get(state.lesson),next=lessons[lessons.indexOf(l)+1];return `<section class="end-card"><div class="end-mark" aria-hidden="true">✓</div><div class="eyebrow">Round complete</div><h1>${completed===state.run.length?'One more piece makes sense.':'A good place to pause.'}</h1><p class="lead" style="margin:0 auto 18px;font-size:16px">${completed} of ${state.run.length} checkpoints completed in this set.${review?` ${review} ${review===1?'is':'are'} waiting for another try.`:' No questions from this set are waiting for review.'}</p><p class="small">Completion records practice, not a promise of mastery. Explain the answer in your own words before moving on.</p>${progressMeter(s.completed,questions.size,'Overall completion')}<div class="lesson-actions">${state.runMode==='lesson'&&next?`<button type="button" class="primary" data-lesson="${next.id}">Next lesson →</button>`:`<button type="button" class="primary" data-action="trail">Back to the trail →</button>`}${review?`<button type="button" data-action="review">Review my tricky questions</button>`:`<button type="button" data-action="mixed">Try a mixed round</button>`}</div></section>`;}
 function review(){const ids=[...questions.keys()].filter(id=>result(id).needsReview);return `<div class="back-row"><button type="button" class="quiet" data-action="trail">← Trail map</button></div><div class="eyebrow">Remember it by trying again</div><h1>Your review queue</h1><p class="lead">${ids.length?`${ids.length} question${ids.length===1?'':'s'} from a miss, hint, revealed answer or skip. A correct unaided answer in a fresh attempt clears it.`:'No questions waiting. Mix familiar concepts to see what sticks.'}</p><button type="button" class="primary" data-action="${ids.length?'start-review':'mixed'}">${ids.length?'Start a review round':'Try 10 mixed questions'} →</button><div class="review-list">${ids.map(id=>{const q=questions.get(id),l=lessonById.get(q.lesson);return `<div class="review-item"><div><p>${rich(q.prompt)}</p><span class="small">${esc(l.title)}</span></div><button type="button" data-review-one="${id}">Try again</button></div>`;}).join('')}</div>`;}
 function render(focus=false){document.getElementById('review-count').textContent=stats().review;main.innerHTML=state.view==='lesson'?lessonPage():state.view==='question'?questionPage():state.view==='finish'?finish():state.view==='review'?review():trail();if(focus){window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}save();}
 function setView(view){state.view=view;state.draft=null;render(true);}
 function begin(ids,mode){state.run=ids;state.index=0;state.runMode=mode;state.runOutcomes={};state.draft=null;state.view='question';render(true);}
 function submit(){const q=questions.get(state.run[state.index]),d=state.draft;if(!q||d.correct||d.revealed)return;if(q.type==='choice'&&d.choice===null||q.type==='fill'&&!d.text.trim())return;const ok=q.type==='choice'?d.choice===q.answer:q.type==='fill'?q.accepted.some(a=>normal(a)===normal(d.text)):d.order.every((x,i)=>x===i);const r={...result(q.id)},first=r.attempts===0&&!r.completed&&!r.helped&&!r.needsReview;d.tries++;r.attempts++;if(ok){d.correct=true;state.runOutcomes[q.id]=d.hinted||d.tries>1?'helped':'unaided';r.completed=true;if(first&&d.tries===1&&!d.hinted)r.firstTry=true;r.needsReview=d.hinted||d.tries>1;d.feedback={kind:'correct',title:d.tries===1&&!d.hinted?'That’s it.':'You worked it out.',text:q.explanation};}else{r.needsReview=true;d.feedback={kind:'wrong',title:'Not quite. Try one more look.',text:q.type==='choice'?q.options[d.choice].why:q.type==='fill'?'That does not match the requested C# token or expression. Check its role and capitalization; the hint can narrow it down.':'One of these steps needs a value or state that is not ready yet. Follow the dependencies from top to bottom.'};}state.results[q.id]=r;render();document.getElementById('feedback')?.scrollIntoView({block:'nearest',behavior:'instant'});}
 function useHelp(){const q=questions.get(state.run[state.index]);if(!q)return;state.draft.hinted=true;state.results[q.id]={...result(q.id),helped:true,needsReview:true};save();}
 function next(){state.index++;state.draft=null;if(state.index>=state.run.length)state.view='finish';render(true);}
 function settings(){const s=stats();document.getElementById('settings-body').innerHTML=`<p>${s.completed}/${questions.size} checkpoints completed; ${s.firstTry} correct on the first unaided try; ${s.review} waiting for review.</p><p class="small">Progress stays in this browser, under this file or website location. Export it before changing browser, location or device. The file contains only learning progress.</p>${!storageAvailable?'<p class="notice">Browser storage is unavailable. Export progress before closing this page.</p>':''}<div class="settings-actions"><button type="button" data-action="theme">Use ${state.theme==='light'?'dark':'light'} theme</button><button type="button" data-action="export">Export progress</button><button type="button" data-action="import">Import progress</button></div><p class="small">A completed checkpoint can include help. The review queue clears only after a correct unaided attempt. There is no timer or model grading.</p><button type="button" class="quiet danger" data-action="reset">Reset this game’s progress</button>`;if(!dialog.open)dialog.showModal();}
 function exportProgress(){const blob=new Blob([JSON.stringify({version:1,lesson:state.lesson,results:state.results},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='csharp-trail-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Progress exported. Keep this file to restore it later.');}
 document.addEventListener('click',event=>{
   const b=event.target.closest('button,a');if(!b)return;
   if(b.dataset.lesson){state.lesson=b.dataset.lesson;setView('lesson');return;}
   if(b.dataset.reviewOne){begin([b.dataset.reviewOne],'review');return;}
   if(b.hasAttribute('data-cheat-help')&&state.view==='question'){if(!state.draft.correct&&!state.draft.revealed)useHelp();return;}
   if(b.hasAttribute('data-move')){const i=Number(b.dataset.move),j=i+Number(b.dataset.direction),a=state.draft.order;if(j>=0&&j<a.length){[a[i],a[j]]=[a[j],a[i]];render();document.querySelector(`[data-move="${j}"][data-direction="${b.dataset.direction}"]:not(:disabled)`)?.focus();}return;}
   const action=b.dataset.action;if(!action)return;
   if(action==='trail')setView('trail');
   if(action==='review')setView('review');
   if(action==='start-lesson')begin(lessonById.get(state.lesson).questions.map(q=>q.id),'lesson');
   if(action==='mixed')begin(shuffle([...questions.keys()]).slice(0,10),'mixed');
   if(action==='start-review')begin(shuffle([...questions.keys()].filter(id=>result(id).needsReview)).slice(0,10),'review');
   if(action==='check')submit();
   if(action==='hint'){useHelp();render();}
   if(action==='note'){if(!state.draft.showNote)useHelp();state.draft.showNote=!state.draft.showNote;render();}
   if(action==='reveal'){useHelp();const q=questions.get(state.run[state.index]);state.draft.revealed=true;state.runOutcomes[q.id]='helped';state.results[q.id]={...result(q.id),completed:true,helped:true,needsReview:true};state.draft.feedback={kind:'reveal',title:'Let’s walk through it.',text:q.explanation};render();}
   if(action==='skip'){const id=state.run[state.index];state.runOutcomes[id]='skipped';state.results[id]={...result(id),needsReview:true};next();}
   if(action==='next')next();
   if(action==='settings')settings();
   if(action==='close-settings')dialog.close();
   if(action==='theme'){state.theme=state.theme==='light'?'dark':'light';document.documentElement.dataset.theme=state.theme;save();settings();}
   if(action==='export')exportProgress();
   if(action==='import')document.getElementById('import-file').click();
   if(action==='reset'&&window.confirm('Reset all progress for C# Trail in this browser?')){state.results={};state.lesson=lessons[0].id;dialog.close();setView('trail');toast('Progress reset. The lessons are ready whenever you are.');}
 });
 main.addEventListener('change',event=>{if(event.target.matches('input[name=answer]')){state.draft.choice=Number(event.target.value);const b=main.querySelector('[data-action=check]');if(b)b.disabled=false;}});
 main.addEventListener('input',event=>{if(event.target.id==='answer-input'){state.draft.text=event.target.value;const b=main.querySelector('[data-action=check]');if(b)b.disabled=!event.target.value.trim();}});
 main.addEventListener('keydown',event=>{if(event.key==='Enter'&&event.target.id==='answer-input'){event.preventDefault();submit();}});
 document.getElementById('import-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>250000)throw Error('too large');const incoming=JSON.parse(await file.text());if(incoming.version!==1||!incoming.results||typeof incoming.results!=='object'||Array.isArray(incoming.results))throw Error('format');const valid=Object.entries(incoming.results).every(([id,r])=>questions.has(id)&&r&&typeof r==='object'&&!Array.isArray(r)&&Number.isInteger(r.attempts)&&r.attempts>=0&&r.attempts<=100000&&['completed','firstTry','needsReview','helped'].every(k=>typeof r[k]==='boolean')&&(!r.firstTry||r.completed&&r.attempts>=1)&&(!r.completed||r.attempts>=1||r.helped));if(!valid)throw Error('invalid progress');const clean=cleanResults(incoming.results);if(!window.confirm('Replace current progress with the progress in this file?'))return;state.results=clean;if(lessonById.has(incoming.lesson))state.lesson=incoming.lesson;dialog.close();setView('trail');toast('Progress restored.');}catch{toast('Could not import that file. Choose a C# Trail progress export.');}finally{event.target.value='';}});
 function readHash(){const id=location.hash.slice(1);if(lessonById.has(id)){state.lesson=id;state.view='lesson';state.draft=null;}else if(id==='trail')state.view='trail';render();}
 window.addEventListener('hashchange',readHash);readHash();
})();
